### ISSUE TITLE
Adding https://github.com/KRRUg/KLMS

### ISSUE THREAD

**Issue by andygrunwald** [LANparties/awesome-lanparty-software#26]
https://github.com/KRRUg/KLMS is a new lan cms

**Comment by homeworkprod** [comment]
Good point, @andygrunwald! Didn't yet get around to adding it myself. Feel free to provide a PR if you like.

**Comment by andygrunwald** [comment]
@homeworkprod Here we go: https://github.com/LANparties/awesome-lanparty-software/pull/27
